FROM php8.2-fpm

# تثبيت الاعتماديات ومكتبات PHP المطلوبة
RUN apt-get update && apt-get install -y 
    git curl libpng-dev libonig-dev libxml2-dev zip unzip nginx

RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

WORKDIR varwww

COPY . varwww

# تثبيت Composer
COPY --from=composerlatest usrbincomposer usrbincomposer
RUN composer install --no-dev --optimize-autoloader

# ضبط صلاحيات المجلدات
RUN chown -R www-datawww-data varwwwstorage varwwwbootstrapcache

EXPOSE 80

CMD php artisan migrate --force && php artisan configcache && php artisan serve --host=0.0.0.0 --port=80