[program:school-management-worker]
directory=/var/www/school_management
command=/usr/bin/php artisan queue:work database --sleep=3 --tries=3 --timeout=120 --backoff=10
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/school-management-worker.log
stopwaitsecs=360

